const fs = require('fs');
const path = require('path');

// Simple .env parser to avoid dependencies
const envPath = path.join(__dirname, '.env');
if (fs.existsSync(envPath)) {
    const envFile = fs.readFileSync(envPath, 'utf8');
    envFile.split('\n').forEach(line => {
        const [key, ...values] = line.split('=');
        if (key && values.length > 0) {
            process.env[key.trim()] = values.join('=').trim();
        }
    });
}

const supabaseUrl = process.env.SUPABASE_URL || 'YOUR_SUPABASE_URL_PLACEHOLDER';
const supabaseKey = process.env.SUPABASE_KEY || 'YOUR_SUPABASE_KEY_PLACEHOLDER';
const groqApiKey = process.env.GROQ_API_KEY || 'YOUR_GROQ_API_KEY_PLACEHOLDER';

const configContent = `// Konfigurasi Aplikasi (Generated by Build Script)
const SUPABASE_URL = '${supabaseUrl}';
const SUPABASE_ANON_KEY = '${supabaseKey}';
const GROQ_API_KEY = '${groqApiKey}';

const supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

function checkAuth() {
    const session = localStorage.getItem('user_session');
    if (!session) return null;
    return JSON.parse(session);
}

window.isSupabaseReady = true;
document.dispatchEvent(new Event('supabaseReady'));
`;

fs.writeFileSync('config.js', configContent);
console.log('✅ config.js has been generated successfully from Environment Variables.');
