const fs = require('fs');
const path = require('path');

// Simple .env parser to avoid dependencies
const envPath = path.join(__dirname, '.env');
if (fs.existsSync(envPath)) {
    const envFile = fs.readFileSync(envPath, 'utf8');
    envFile.split('\n').forEach(line => {
        const [key, ...values] = line.split('=');
        if (key && values.length > 0) {
            process.env[key.trim()] = values.join('=').trim();
        }
    });
}

const supabaseUrl = process.env.SUPABASE_URL || 'YOUR_SUPABASE_URL_PLACEHOLDER';
const supabaseKey = process.env.SUPABASE_KEY || 'YOUR_SUPABASE_KEY_PLACEHOLDER';
const groqApiKey = process.env.GROQ_API_KEY || 'YOUR_GROQ_API_KEY_PLACEHOLDER';

const configContent = `// Konfigurasi Aplikasi (Generated by Build Script)
const SUPABASE_URL = '${supabaseUrl}';
const SUPABASE_ANON_KEY = '${supabaseKey}';
const GROQ_API_KEY = '${groqApiKey}';

// Visual Modal Class (Embedded for Reliability) - DEFINED FIRST
class VisualModal {
    static init() {
        if (typeof document === 'undefined') return false; // Server-side safety
        if (document.getElementById('visual-modal-overlay')) return true; // Already init

        if (!document.body) return false; // Body not ready

        const html = \`
            <div id="visual-modal-overlay" class="fixed inset-0 z-[9999] hidden items-center justify-center bg-slate-900/40 backdrop-blur-sm opacity-0 transition-opacity duration-300">
                <div id="visual-modal-card" class="bg-white rounded-3xl shadow-2xl w-full max-w-sm p-6 transform scale-95 opacity-0 transition-all duration-300 m-4">
                    <div class="text-center">
                        <div id="vm-icon-container" class="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-slate-100 mb-4 text-3xl">
                            <!-- Icon Injected Here -->
                        </div>
                        <h3 id="vm-title" class="text-lg font-black text-slate-800 leading-6"></h3>
                        <div class="mt-2">
                            <p id="vm-message" class="text-sm text-slate-500"></p>
                        </div>
                    </div>
                    <div id="vm-actions" class="mt-6 flex gap-3 justify-center">
                        <!-- Buttons Injected Here -->
                    </div>
                </div>
            </div>
        \`;
        document.body.insertAdjacentHTML('beforeend', html);
        return true;
    }

    static async show({ title, message, type = 'info', confirmText = 'Oke', cancelText = 'Batal', showCancel = false }) {
        // 1. Ensure DOM is ready (Wait capability)
        if (!this.init()) {
            console.log('VisualModal: DOM not ready. Waiting...');
            await new Promise(resolve => window.addEventListener('DOMContentLoaded', resolve));
            this.init(); // Retry init
        }

        return new Promise((resolve) => {
            try {
                const overlay = document.getElementById('visual-modal-overlay');
                if (!overlay) {
                    if (showCancel) resolve(confirm(\`\${title}\\n\\n\${message}\`));
                    else { alert(\`\${title}\\n\\n\${message}\`); resolve(true); }
                    return;
                }

                const card = document.getElementById('visual-modal-card');
                const iconContainer = document.getElementById('vm-icon-container');
                const titleEl = document.getElementById('vm-title');
                const msgEl = document.getElementById('vm-message');
                const actionsEl = document.getElementById('vm-actions');

                // Content
                titleEl.textContent = title || (type === 'error' ? 'Oops!' : 'Info');
                msgEl.textContent = message;

                // Icons & Colors
                let icon = '';
                let iconBg = 'bg-slate-100';
                let iconColor = 'text-slate-500';
                let btnColor = 'bg-slate-700 hover:bg-slate-800';

                if (type === 'success') {
                    icon = '<i class="fa-solid fa-check"></i>';
                    iconBg = 'bg-emerald-100';
                    iconColor = 'text-emerald-600';
                    btnColor = 'bg-emerald-500 hover:bg-emerald-600 shadow-emerald-500/30';
                } else if (type === 'error') {
                    icon = '<i class="fa-solid fa-xmark"></i>';
                    iconBg = 'bg-red-100';
                    iconColor = 'text-red-500';
                    btnColor = 'bg-red-500 hover:bg-red-600 shadow-red-500/30';
                } else if (type === 'warning' || type === 'confirm') {
                    icon = '<i class="fa-solid fa-question"></i>';
                    iconBg = 'bg-amber-100';
                    iconColor = 'text-amber-500';
                    btnColor = 'bg-blue-600 hover:bg-blue-700 shadow-blue-500/30';
                } else {
                    icon = '<i class="fa-solid fa-info"></i>';
                    btnColor = 'bg-blue-600 hover:bg-blue-700 shadow-blue-500/30';
                    iconBg = 'bg-blue-100';
                    iconColor = 'text-blue-500';
                }

                iconContainer.innerHTML = icon;
                iconContainer.className = \`mx-auto flex h-16 w-16 items-center justify-center rounded-full mb-4 text-3xl animate-bounce-short \${iconBg} \${iconColor}\`;

                // Buttons
                let buttonsHtml = '';
                if (showCancel) {
                    buttonsHtml += \`
                        <button id="vm-btn-cancel" class="flex-1 px-4 py-4 bg-slate-100 text-slate-500 font-bold rounded-xl hover:bg-slate-200 transition-colors">
                            \${cancelText}
                        </button>
                    \`;
                }
                buttonsHtml += \`
                    <button id="vm-btn-confirm" class="flex-1 px-4 py-4 text-white font-bold rounded-xl transition-all shadow-lg \${btnColor}">
                        \${confirmText}
                    </button>
                \`;
                actionsEl.innerHTML = buttonsHtml;

                // Cleanup
                const cleanup = () => {
                    overlay.classList.add('opacity-0');
                    card.classList.add('scale-95', 'opacity-0');
                    setTimeout(() => {
                        overlay.classList.add('hidden');
                        overlay.classList.remove('flex');
                    }, 300);
                };

                // Listeners
                const confirmBtn = document.getElementById('vm-btn-confirm');
                if (confirmBtn) confirmBtn.onclick = () => { cleanup(); resolve(true); };

                if (showCancel) {
                    const cancelBtn = document.getElementById('vm-btn-cancel');
                    if (cancelBtn) cancelBtn.onclick = () => { cleanup(); resolve(false); };
                }

                // Show
                overlay.classList.remove('hidden');
                overlay.classList.add('flex');
                setTimeout(() => {
                    overlay.classList.remove('opacity-0');
                    card.classList.remove('scale-95', 'opacity-0');
                    card.classList.add('scale-100', 'opacity-100');
                }, 10);

            } catch (e) {
                console.error('VisualModal Error:', e);
                if (showCancel) resolve(confirm(\`\${title}\\n\\n\${message}\`));
                else { alert(\`\${title}\\n\\n\${message}\`); resolve(true); }
            }
        });
    }

    static async alert(message, title = 'Info', type = 'info') {
        const inferredType = (title || '').toLowerCase().includes('error') || (title || '').toLowerCase().includes('oops') ? 'error' : type;
        return this.show({ title, message, type: inferredType });
    }

    static async confirm(message, title = 'Konfirmasi', type = 'confirm') {
        return this.show({ title, message, type, showCancel: true });
    }
}
window.VisualModal = VisualModal;

// --- Config & Supabase ---
let supabaseClient;
if (typeof supabase !== 'undefined') {
    try {
        if(!SUPABASE_URL.startsWith('http')) throw new Error("Invalid Supabase URL");
        supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
        window.supabaseClient = supabaseClient;
    } catch(e) {
        console.error("CRITICAL: Supabase Init Failed. Check Keys.", e);
        if(document.body) {
             VisualModal.alert('Koneksi Database Gagal. Cek Console.', 'System Error', 'error');
        } else {
             document.addEventListener('DOMContentLoaded', () => {
                 VisualModal.alert('Koneksi Database Gagal. Cek Console.', 'System Error', 'error');
             });
        }
    }
} else {
    console.error('Supabase SDK not loaded.');
    if (document.body) {
         VisualModal.alert('Gagal memuat Script Database (Supabase).\nCek koneksi internet atau matikan AdBlock.', 'Koneksi Error', 'error');
    } else {
         document.addEventListener('DOMContentLoaded', () => {
             VisualModal.alert('Gagal memuat Script Database (Supabase).\nCek koneksi internet atau matikan AdBlock.', 'Koneksi Error', 'error');
         });
    }
}

function checkAuth() {
    try {
        const session = localStorage.getItem('user_session');
        if (!session) return null;
        return JSON.parse(session);
    } catch (e) {
        console.error("Session corrupted, clearing...", e);
        localStorage.removeItem('user_session');
        return null;
    }
}

// Event untuk menandakan config siap
window.isSupabaseReady = true;
document.dispatchEvent(new Event('supabaseReady'));

// GLOBAL SECURITY
(async function () {
    const path = window.location.pathname;
    const page = path.split('/').pop();

    if (page === 'login.html' || page === 'maintenance.html') return;

    const session = checkAuth();
    if (!session) {
        // Only redirect if NOT building/placeholder
        if(SUPABASE_URL.startsWith('http')) {
             window.location.href = 'login.html';
        }
        return;
    }

    if (page === 'admin.html' || path.endsWith('/admin.html')) {
        const isAdmin = session.role === 'admin';
        const name = (session.nama || '').toLowerCase();
        const isFaldhi = name.includes('faldhi muhammad ariefaldhi') || name.includes('faldhi');

        if (!isAdmin && !isFaldhi) {
            alert('⛔ AKSES DITOLAK\\nHalaman ini khusus untuk Admin.');
            window.location.replace('index.html');
            return;
        }
    }
})();

// VISUAL DEBUG (Only shows if keys are missing via Build Check)
if (SUPABASE_URL.includes('PLACEHOLDER') || !SUPABASE_URL.startsWith('http')) {
    const showConfigAlert = () => {
        const alertDiv = document.createElement('div');
        alertDiv.className = 'fixed top-0 left-0 w-full bg-red-600 text-white text-center py-2 z-[100] font-bold text-sm shadow-lg';
        alertDiv.innerHTML = '<i class="fa-solid fa-triangle-exclamation mr-2"></i> ERROR: Vercel Env Vars Missing (Build Script ran but keys not found).';
        document.body.appendChild(alertDiv);
    };
    if (document.body) showConfigAlert();
    else document.addEventListener('DOMContentLoaded', showConfigAlert);
}
`;

fs.writeFileSync('config.js', configContent);
console.log('✅ config.js has been generated successfully from Environment Variables.');
